---
# tasks file for test
  # - name: make req
  #   ansible.builtin.uri:
  #     url: https://api.restful-api.dev/objects/1
  #     # method: GET
  #     register: _command

  - name: Get response with 'uri' module
    uri:
      url: "https://api.restful-api.dev/objects/1"
      method: GET
      body_format: raw     # default
      return_content: true # default 'false'
      status_code: 200
    # register: _command

  - name: la poste
    uri: 
      url: "https://api.restful-api.dev/objects"
      method: POST
      return_content: yes
      body:
        name: Apple MacBook Pro 16
        data:
          year: 2019
          price: 123123
          CPU model: Intel Core i9
          Hard disk size: 1 TB
      status_code: 200
      body_format: json
      validate_certs: no

    register: _command

  - name: debug
    ansible.builtin.debug:
      var: _command
