---
# tasks file for test
  # - name: make req
  #   ansible.builtin.uri:
  #     url: https://api.restful-api.dev/objects/1
  #     # method: GET
  #     register: _command

  - name: la poste
    uri: 
      url: "http://46.19.67.121:9009/launch_task"
      method: POST
      return_content: yes
      body:
        task_data: "sample data"
      status_code: 200
      body_format: json
      validate_certs: no

    register: _command

  - name: Get response with 'uri' module
    uri:
      url: "http://46.19.67.121:9009/get_task_data?task_id={{ _command.json.task_id }}"
      method: GET
      body_format: raw     # default
      return_content: true # default 'false'
      status_code: 200
    register: result
    until: result.json.state == "SUCCESS"
    delay: 1
    
  - name: debug
    ansible.builtin.debug:
      var: result
